name = "NeuralDynamics"
uuid = "4a0b20f9-fc5a-4814-8f96-b33a141a51c8"
authors = ["Michael Young"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
